///////////////////////////////////////////////////////////
//  GprsCommuniPort.cs
//  Implementation of the Class GprsCommuniPort
//  Generated by Enterprise Architect
//  Created on:      08-七月-2009 15:36:23
//  Original author: LiZhL
///////////////////////////////////////////////////////////


using System;
using System.Net.Sockets;

namespace Xdgk.Communi
{

    ///// <summary>
    ///// gprs通讯类
    ///// </summary>
    //public class GprsCommuniPort : CommuniPort
    //{
    //    public GprsCommuniPort()
    //    {

    //    }
    //}//end GprsCommuniPort


}
