///////////////////////////////////////////////////////////
//  BytesConverter.cs
//  Implementation of the Class BytesConverter
//  Generated by Enterprise Architect
//  Created on:      08-七月-2009 11:36:06
//  Original author: LiZhL
///////////////////////////////////////////////////////////


using System;
using Xdgk.Communi.Interface;

namespace Xdgk.Communi
{
    ///// <summary>
    ///// 提供byte[]到value之间的双向转换
    ///// </summary>
    //public abstract class BytesConverter : IBytesConverter
    //{
    //    /// <summary>
    //    /// 
    //    /// </summary>
    //    static readonly public OriginalConverter OriginalConverter = new OriginalConverter();

    //    public BytesConverter()
    //    {

    //    }

    //    /// <summary>
    //    /// 
    //    /// </summary>
    //    /// <param name="bytes"></param>
    //    /// <returns></returns>
    //    public abstract object ConvertToObject(byte[] bytes);

    //    /// <summary>
    //    /// 
    //    /// </summary>
    //    /// <param name="obj"></param>
    //    /// <returns></returns>
    //    public abstract byte[] ConvertToBytes(object obj);

    //}


    //#region
    ///// <summary>
    ///// 
    ///// </summary>
    //public class BitsConverter : BytesConverter
    //{
    //    public override byte[] ConvertToBytes(object obj)
    //    {
    //        return null;
    //    }

    //    public override object ConvertToObject(byte[] bytes)
    //    {
    //        return null;
    //    }
    //}
    //#endregion //

}