//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdgk.Communi {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xdgk.Communi.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 实际 的本地化字符串。
        /// </summary>
        internal static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址错误 的本地化字符串。
        /// </summary>
        internal static string AddressErrorResult {
            get {
                return ResourceManager.GetString("AddressErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部记录 的本地化字符串。
        /// </summary>
        internal static string CommuniDetailAll {
            get {
                return ResourceManager.GetString("CommuniDetailAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅失败记录 的本地化字符串。
        /// </summary>
        internal static string CommuniDetailFail {
            get {
                return ResourceManager.GetString("CommuniDetailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅成功记录 的本地化字符串。
        /// </summary>
        internal static string CommuniDetailSuccess {
            get {
                return ResourceManager.GetString("CommuniDetailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯记录 - {0}({1}) 的本地化字符串。
        /// </summary>
        internal static string CommuniLogTitle {
            get {
                return ResourceManager.GetString("CommuniLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换器 的本地化字符串。
        /// </summary>
        internal static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换错误 的本地化字符串。
        /// </summary>
        internal static string ConvertErrorResult {
            get {
                return ResourceManager.GetString("ConvertErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验错误 的本地化字符串。
        /// </summary>
        internal static string CRCErrorResult {
            get {
                return ResourceManager.GetString("CRCErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环 的本地化字符串。
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据错误 的本地化字符串。
        /// </summary>
        internal static string DataErrorResult {
            get {
                return ResourceManager.GetString("DataErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期望 的本地化字符串。
        /// </summary>
        internal static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即 的本地化字符串。
        /// </summary>
        internal static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度错误 的本地化字符串。
        /// </summary>
        internal static string LengthErrorResult {
            get {
                return ResourceManager.GetString("LengthErrorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Opera {
            get {
                return ResourceManager.GetString("Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收 的本地化字符串。
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选中一个设备！ 的本地化字符串。
        /// </summary>
        internal static string SelectADevice {
            get {
                return ResourceManager.GetString("SelectADevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string SuccessResult {
            get {
                return ResourceManager.GetString("SuccessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
