//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeHeCommuniServer {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YeHeCommuniServer.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 报警 的本地化字符串。
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冶河采集 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冶河数据采集程序 的本地化字符串。
        /// </summary>
        internal static string AppNameLong {
            get {
                return ResourceManager.GetString("AppNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已经运行 的本地化字符串。
        /// </summary>
        internal static string AppRunning {
            get {
                return ResourceManager.GetString("AppRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 的本地化字符串。
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要退出吗? 的本地化字符串。
        /// </summary>
        internal static string AreYouExit {
            get {
                return ResourceManager.GetString("AreYouExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次回压 的本地化字符串。
        /// </summary>
        internal static string BP1 {
            get {
                return ResourceManager.GetString("BP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次回压 的本地化字符串。
        /// </summary>
        internal static string BP2 {
            get {
                return ResourceManager.GetString("BP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次回温 的本地化字符串。
        /// </summary>
        internal static string BT1 {
            get {
                return ResourceManager.GetString("BT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次回温 的本地化字符串。
        /// </summary>
        internal static string BT2 {
            get {
                return ResourceManager.GetString("BT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过IP地址 的本地化字符串。
        /// </summary>
        internal static string ByIP {
            get {
                return ResourceManager.GetString("ByIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过本地端口 的本地化字符串。
        /// </summary>
        internal static string ByLocalPort {
            get {
                return ResourceManager.GetString("ByLocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过远程端口 的本地化字符串。
        /// </summary>
        internal static string ByRemotePort {
            get {
                return ResourceManager.GetString("ByRemotePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环泵 的本地化字符串。
        /// </summary>
        internal static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令已提交 的本地化字符串。
        /// </summary>
        internal static string CommandSubmit {
            get {
                return ResourceManager.GetString("CommandSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯记录 - {0} {1} 的本地化字符串。
        /// </summary>
        internal static string CommuniLogTitle {
            get {
                return ResourceManager.GetString("CommuniLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环({0}) 的本地化字符串。
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环泵：{0} 的本地化字符串。
        /// </summary>
        internal static string CyclePump {
            get {
                return ResourceManager.GetString("CyclePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据:  的本地化字符串。
        /// </summary>
        internal static string Datas {
            get {
                return ResourceManager.GetString("Datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除设备 &apos;{0}&apos; 吗? 的本地化字符串。
        /// </summary>
        internal static string DeleteDevice {
            get {
                return ResourceManager.GetString("DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除站点 &apos;{0}&apos; 吗? 的本地化字符串。
        /// </summary>
        internal static string DeleteStation {
            get {
                return ResourceManager.GetString("DeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除任务 &apos;{0}&apos; 吗? 的本地化字符串。
        /// </summary>
        internal static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备:  的本地化字符串。
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间:  的本地化字符串。
        /// </summary>
        internal static string DT {
            get {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误:  的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} ... 的本地化字符串。
        /// </summary>
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在 &apos;{0}&apos; 地址 &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExistAddress {
            get {
                return ResourceManager.GetString("ExistAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点 &apos;{0}&apos; 已经存在 的本地化字符串。
        /// </summary>
        internal static string ExistStationName {
            get {
                return ResourceManager.GetString("ExistStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次供压 的本地化字符串。
        /// </summary>
        internal static string GP1 {
            get {
                return ResourceManager.GetString("GP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次供压 的本地化字符串。
        /// </summary>
        internal static string GP2 {
            get {
                return ResourceManager.GetString("GP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次供温 的本地化字符串。
        /// </summary>
        internal static string GT1 {
            get {
                return ResourceManager.GetString("GT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次供温 的本地化字符串。
        /// </summary>
        internal static string GT2 {
            get {
                return ResourceManager.GetString("GT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 www.xdgk.com.cn 的本地化字符串。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单次 的本地化字符串。
        /// </summary>
        internal static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的IP地址 的本地化字符串。
        /// </summary>
        internal static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后执行:  的本地化字符串。
        /// </summary>
        internal static string LastExecut {
            get {
                return ResourceManager.GetString("LastExecut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在监听 {0} 的本地化字符串。
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个设备! 的本地化字符串。
        /// </summary>
        internal static string NotSelectedDevice {
            get {
                return ResourceManager.GetString("NotSelectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作:  的本地化字符串。
        /// </summary>
        internal static string Opera {
            get {
                return ResourceManager.GetString("Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择设备类型！ 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectDeviceType {
            get {
                return ResourceManager.GetString("PleaseSelectDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个站点！ 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectStation {
            get {
                return ResourceManager.GetString("PleaseSelectStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个任务！ 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectTask {
            get {
                return ResourceManager.GetString("PleaseSelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补水泵：{0} 的本地化字符串。
        /// </summary>
        internal static string RecruitePump {
            get {
                return ResourceManager.GetString("RecruitePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补水泵 的本地化字符串。
        /// </summary>
        internal static string RM {
            get {
                return ResourceManager.GetString("RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站名不能为空 的本地化字符串。
        /// </summary>
        internal static string StationNameCanNotEmpty {
            get {
                return ResourceManager.GetString("StationNameCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点 &apos;{0}&apos; 尚未连接 的本地化字符串。
        /// </summary>
        internal static string StationNotConnect {
            get {
                return ResourceManager.GetString("StationNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务名称:  的本地化字符串。
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务类型:  的本地化字符串。
        /// </summary>
        internal static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定义的设备类型 &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnDefineDeviceType {
            get {
                return ResourceManager.GetString("UnDefineDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唐山现代工控技术有限公司 的本地化字符串。
        /// </summary>
        internal static string XdgkCompany {
            get {
                return ResourceManager.GetString("XdgkCompany", resourceCulture);
            }
        }
    }
}
