//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongShuiGuanLiV2 {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YongShuiGuanLiV2.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用水量 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用水量(m3) 的本地化字符串。
        /// </summary>
        internal static string AmountWithUnit {
            get {
                return ResourceManager.GetString("AmountWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道名称 的本地化字符串。
        /// </summary>
        internal static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配水量 的本地化字符串。
        /// </summary>
        internal static string DistributeAmount {
            get {
                return ResourceManager.GetString("DistributeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配水开始 的本地化字符串。
        /// </summary>
        internal static string DistributeBegin {
            get {
                return ResourceManager.GetString("DistributeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配水结束 的本地化字符串。
        /// </summary>
        internal static string DistributeEnd {
            get {
                return ResourceManager.GetString("DistributeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string DT {
            get {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放水季 的本地化字符串。
        /// </summary>
        internal static string DuringWater {
            get {
                return ResourceManager.GetString("DuringWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闸前水位 的本地化字符串。
        /// </summary>
        internal static string GateBeforeWL {
            get {
                return ResourceManager.GetString("GateBeforeWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闸前水位(cm) 的本地化字符串。
        /// </summary>
        internal static string GateBeforeWLWithUnit {
            get {
                return ResourceManager.GetString("GateBeforeWLWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闸后水位 的本地化字符串。
        /// </summary>
        internal static string GateBehindWL {
            get {
                return ResourceManager.GetString("GateBehindWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闸后水位(cm) 的本地化字符串。
        /// </summary>
        internal static string GateBehindWLWithUnit {
            get {
                return ResourceManager.GetString("GateBehindWLWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闸门高度 的本地化字符串。
        /// </summary>
        internal static string GateHeight {
            get {
                return ResourceManager.GetString("GateHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闸门高度(cm) 的本地化字符串。
        /// </summary>
        internal static string GateHeightWithUnit {
            get {
                return ResourceManager.GetString("GateHeightWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瞬时流量 的本地化字符串。
        /// </summary>
        internal static string InstantFlux {
            get {
                return ResourceManager.GetString("InstantFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瞬时流量(m3/s) 的本地化字符串。
        /// </summary>
        internal static string InstantFluxWithUnit {
            get {
                return ResourceManager.GetString("InstantFluxWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需水量 的本地化字符串。
        /// </summary>
        internal static string NeedAmount {
            get {
                return ResourceManager.GetString("NeedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string NeedBegin {
            get {
                return ResourceManager.GetString("NeedBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string NeedEnd {
            get {
                return ResourceManager.GetString("NeedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需水单位 的本地化字符串。
        /// </summary>
        internal static string NeedWaterUser {
            get {
                return ResourceManager.GetString("NeedWaterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建配水 的本地化字符串。
        /// </summary>
        internal static string NewDistribute {
            get {
                return ResourceManager.GetString("NewDistribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新值 的本地化字符串。
        /// </summary>
        internal static string NewWaterLevel {
            get {
                return ResourceManager.GetString("NewWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降雨量 的本地化字符串。
        /// </summary>
        internal static string RainFill {
            get {
                return ResourceManager.GetString("RainFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降雨量(mm) 的本地化字符串。
        /// </summary>
        internal static string RainFillWithUnit {
            get {
                return ResourceManager.GetString("RainFillWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站名 的本地化字符串。
        /// </summary>
        internal static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已用水量 的本地化字符串。
        /// </summary>
        internal static string UsedAmount {
            get {
                return ResourceManager.GetString("UsedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用水户 的本地化字符串。
        /// </summary>
        internal static string WaterUserName {
            get {
                return ResourceManager.GetString("WaterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水位 的本地化字符串。
        /// </summary>
        internal static string WL {
            get {
                return ResourceManager.GetString("WL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水位1 的本地化字符串。
        /// </summary>
        internal static string WL1 {
            get {
                return ResourceManager.GetString("WL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水位2 的本地化字符串。
        /// </summary>
        internal static string WL2 {
            get {
                return ResourceManager.GetString("WL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水位(cm) 的本地化字符串。
        /// </summary>
        internal static string WLWithUnit {
            get {
                return ResourceManager.GetString("WLWithUnit", resourceCulture);
            }
        }
    }
}
