//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3082
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongShuiGuanLiV2 {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YongShuiGuanLiV2.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用水量查询 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用水量比较 的本地化字符串。
        /// </summary>
        internal static string CompareAmount {
            get {
                return ResourceManager.GetString("CompareAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水位比较 的本地化字符串。
        /// </summary>
        internal static string CompareWL {
            get {
                return ResourceManager.GetString("CompareWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史用水量查询 的本地化字符串。
        /// </summary>
        internal static string DataHistoryAmount {
            get {
                return ResourceManager.GetString("DataHistoryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史流量查询 的本地化字符串。
        /// </summary>
        internal static string DataHistoryFlux {
            get {
                return ResourceManager.GetString("DataHistoryFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史水位查询 的本地化字符串。
        /// </summary>
        internal static string DataHistoryWL {
            get {
                return ResourceManager.GetString("DataHistoryWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑配水 的本地化字符串。
        /// </summary>
        internal static string DistributeEdit {
            get {
                return ResourceManager.GetString("DistributeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑配水信息 的本地化字符串。
        /// </summary>
        internal static string DistributeItemEdit {
            get {
                return ResourceManager.GetString("DistributeItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建配水信息 的本地化字符串。
        /// </summary>
        internal static string DistributeItemNew {
            get {
                return ResourceManager.GetString("DistributeItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本单位配水信息查询 的本地化字符串。
        /// </summary>
        internal static string DistributeList {
            get {
                return ResourceManager.GetString("DistributeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级单位配水信息查询 的本地化字符串。
        /// </summary>
        internal static string DistributeLowLevel {
            get {
                return ResourceManager.GetString("DistributeLowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建配水 的本地化字符串。
        /// </summary>
        internal static string DistributeNew {
            get {
                return ResourceManager.GetString("DistributeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段用水量查询 的本地化字符串。
        /// </summary>
        internal static string DuringAmount {
            get {
                return ResourceManager.GetString("DuringAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段流量查询 的本地化字符串。
        /// </summary>
        internal static string DuringFlux {
            get {
                return ResourceManager.GetString("DuringFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放水季定义 的本地化字符串。
        /// </summary>
        internal static string DuringWaterDefine {
            get {
                return ResourceManager.GetString("DuringWaterDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段水位查询 的本地化字符串。
        /// </summary>
        internal static string DuringWL {
            get {
                return ResourceManager.GetString("DuringWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日流量查询 的本地化字符串。
        /// </summary>
        internal static string Flux2Hour {
            get {
                return ResourceManager.GetString("Flux2Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来水查询 的本地化字符串。
        /// </summary>
        internal static string InWater {
            get {
                return ResourceManager.GetString("InWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放水季用水量查询 的本地化字符串。
        /// </summary>
        internal static string MulitDuringAmount {
            get {
                return ResourceManager.GetString("MulitDuringAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历年用水量查询 的本地化字符串。
        /// </summary>
        internal static string MulitYearAmount {
            get {
                return ResourceManager.GetString("MulitYearAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需配水查询 的本地化字符串。
        /// </summary>
        internal static string NeedDistribute {
            get {
                return ResourceManager.GetString("NeedDistribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级单位需配水查询 的本地化字符串。
        /// </summary>
        internal static string NeedDistributeLowLevel {
            get {
                return ResourceManager.GetString("NeedDistributeLowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑需水 的本地化字符串。
        /// </summary>
        internal static string NeedWaterEdit {
            get {
                return ResourceManager.GetString("NeedWaterEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本单位需水信息查询 的本地化字符串。
        /// </summary>
        internal static string NeedWaterList {
            get {
                return ResourceManager.GetString("NeedWaterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级单位需水信息查询 的本地化字符串。
        /// </summary>
        internal static string NeedWaterLowLevel {
            get {
                return ResourceManager.GetString("NeedWaterLowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建需水 的本地化字符串。
        /// </summary>
        internal static string NeedWaterNew {
            get {
                return ResourceManager.GetString("NeedWaterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道信息 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时数据查询 的本地化字符串。
        /// </summary>
        internal static string RealData {
            get {
                return ResourceManager.GetString("RealData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        internal static string WaterUser {
            get {
                return ResourceManager.GetString("WaterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日水位查询 的本地化字符串。
        /// </summary>
        internal static string WL2Hour {
            get {
                return ResourceManager.GetString("WL2Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年用水量查询 的本地化字符串。
        /// </summary>
        internal static string YearAmount {
            get {
                return ResourceManager.GetString("YearAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年流量查询 的本地化字符串。
        /// </summary>
        internal static string YearFlux {
            get {
                return ResourceManager.GetString("YearFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年水位查询 的本地化字符串。
        /// </summary>
        internal static string YearWL {
            get {
                return ResourceManager.GetString("YearWL", resourceCulture);
            }
        }
    }
}
