//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWTrans {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWTrans.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 传输周期: {0} 的本地化字符串。
        /// </summary>
        internal static string ExecuteTimeSpan {
            get {
                return ResourceManager.GetString("ExecuteTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已运行 的本地化字符串。
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出吗? 的本地化字符串。
        /// </summary>
        internal static string SureExit {
            get {
                return ResourceManager.GetString("SureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始传输 的本地化字符串。
        /// </summary>
        internal static string TransBegin {
            get {
                return ResourceManager.GetString("TransBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束传输 的本地化字符串。
        /// </summary>
        internal static string TransEnd {
            get {
                return ResourceManager.GetString("TransEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输 &apos;{0}&apos; 记录 &apos;{1}&apos; 条 的本地化字符串。
        /// </summary>
        internal static string TransmitedCount {
            get {
                return ResourceManager.GetString("TransmitedCount", resourceCulture);
            }
        }
    }
}
